# AB Testi ile Bidding Yöntemlerinin Dönüşümünün Karşılaştırılması

----

## İş Problemi

**Senaryo**

Facebook kısa süre önce mevcut "maximumbidding" adı verilen
teklif verme türüne alternatif olarak yeni bir teklif türü olan
"average bidding"’i tanıttı.

Müşterilerimizden biri olan bombabomba.com, bu yeni özelliği test
etmeye karar verdi ve average bidding'inmaximumbidding'den
daha fazla dönüşüm getirip getirmediğini anlamak için bir A/B
testi yapmak istiyor.

A/B testi 1 aydır devam ediyor ve bombabomba.com şimdi sizden
bu A/B testinin sonuçlarını analiz etmenizi bekliyor.
Bombabomba.com için nihai başarı ölçütü Purchase'dır. Bu
nedenle, istatistiksel testler için Purchase metriğine
odaklanılmalıdır.

## Veri Seti Hikayesi

*Amazon ürün verilerini içeren bu veri seti ürün kategorileri ile çeşitli metadataları içermektedir. Elektronik kategorisindeki en 
fazla yorum alan ürünün kullanıcı puanları ve yorumları vardır.*

In [2]:
### Değişkenler

##### Impression  : Reklam görüntüleme sayısı
##### Click : Görüntülenen reklama tıklama sayısı
##### Purchase : Tıklanan reklamlar sonrası satın alınan ürün sayısı
##### Earning : Satın alınan ürünler sonrası elde edilen kazanç

## To do List:

**GÖREV 1**: Veriyi Hazırlama Analiz Etme

**GÖREV 2**: A/B Testinin Hipotezin Tanımlanması

**GÖREV 3**: Hipotez Testinin Gerçekleştirilmesi

**GÖREV 4**: Sonuçların Analizi

-----

### Veriyi Hazırlama ve Analiz Etme

In [55]:
# Pandas kütüphanesini import edelim;

import pandas as pd
import numpy as np
from scipy.stats import shapiro,levene,mannwhitneyu,ttest_ind
# pandas görüntü ayarlarını yapalım;

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.float_format', lambda x: '%.3f' % x)


# veri setini çalışmaya dahil edelim;
control_group = pd.read_excel(r"C:\Users\kkakt\Desktop\AB_project\database\ab_testing.xlsx",sheet_name="Control Group")
test_group = pd.read_excel(r"C:\Users\kkakt\Desktop\AB_project\database\ab_testing.xlsx",sheet_name="Test Group")

df_control = control_group.copy()
df_test = test_group.copy()

In [57]:
# Kontrol grbunun analizini yapalım;

df_control.describe().T

,count,mean,std,min,25%,50%,75%,max
Impression,40.000,101711.449,20302.158,45475.943,85726.690,99790.701,115212.817,147539.336
Click,40.000,5100.657,1329.985,2189.753,4124.304,5001.221,5923.804,7959.125
Purchase,40.000,550.894,134.108,267.029,470.096,531.206,637.957,801.795
Earning,40.000,1908.568,302.918,1253.990,1685.847,1975.161,2119.803,2497.295

In [58]:
# Test grbunun önizlemesi ve analizini yapalım;

df_control.describe().T

,count,mean,std,min,25%,50%,75%,max
Impression,40.000,101711.449,20302.158,45475.943,85726.690,99790.701,115212.817,147539.336
Click,40.000,5100.657,1329.985,2189.753,4124.304,5001.221,5923.804,7959.125
Purchase,40.000,550.894,134.108,267.029,470.096,531.206,637.957,801.795
Earning,40.000,1908.568,302.918,1253.990,1685.847,1975.161,2119.803,2497.295

In [64]:
# veri setlerinin birleştirelim;
df_control["Group"] = "control"
df_test["Group"] = "test"

df = pd.concat([df_control,df_test],axis=0,ignore_index=True)

df

    Impression    Click  Purchase  Earning    Group
0    82529.459 6090.077   665.211 2311.277  control
1    98050.452 3382.862   315.085 1742.807  control
2    82696.024 4167.966   458.084 1797.827  control
3   109914.400 4910.882   487.091 1696.229  control
4   108457.763 5987.656   441.034 1543.720  control
5    77773.634 4462.207   519.670 2081.852  control
6    95110.586 3555.581   512.929 1815.007  control
7   106649.183 4358.027   747.020 1965.100  control
8   122709.717 5091.559   745.986 1651.663  control
9    79498.249 6653.846   470.501 2456.304  control
10   83676.936 4273.400   386.098 2174.094  control
11  132781.020 5830.007   628.872 1992.225  control
12   87939.422 3993.319   613.712 1654.701  control
13  117827.062 5560.368   739.537 1985.221  control
14  129146.690 5537.609   458.156 1601.407  control
15  101616.466 5323.548   801.795 2182.162  control
16   45475.943 7370.214   400.189 1253.990  control
17  147539.336 3856.727   329.377 2143.590  control
18   82067.900 6609.183   267.029 1791.799  control
19   81872.986 7959.125   729.162 1331.696  control
20  105493.023 2189.753   666.482 2111.874  control
21   96122.658 7453.151   513.579 1629.792  control
22   83676.602 7153.974   487.829 1989.642  control
23   80254.332 3075.311   530.680 2101.319  control
24  123961.869 4898.788   585.639 2042.183  control
25   94472.197 5937.479   686.412 1616.589  control
26  110479.807 3585.032   531.733 2185.695  control
27  136171.272 5784.322   772.033 1704.135  control
28  114341.402 3806.146   620.136 1896.750  control
29   94923.684 5678.982   468.878 1857.202  control
30  108051.824 5919.245   521.258 2015.055  control
31   92044.500 4667.205   729.365 2497.295  control
32  101530.950 5626.901   555.002 2090.371  control
33   94225.521 5255.639   619.867 2090.361  control
34   94138.628 6994.184   593.026 1571.871  control
35  132064.219 3747.158   551.072 2256.976  control
36   86409.942 4608.256   345.046 1781.358  control
37  123678.934 3649.074   476.168 2187.721  control
38  101997.494 4736.353   474.614 2254.564  control
39  121085.881 4285.179   590.406 1289.309  control
40  120103.504 3216.548   702.160 1939.611     test
41  134775.943 3635.082   834.054 2929.406     test
42  107806.621 3057.144   422.934 2526.245     test
43  116445.276 4650.474   429.034 2281.429     test
44  145082.517 5201.388   749.860 2781.698     test
45  115923.007 4213.869   778.373 2157.409     test
46  106116.437 3279.473   491.615 2560.411     test
47  125957.116 4690.570   855.720 2563.580     test
48  117442.865 3907.939   660.478 2242.233     test
49  131271.716 4721.188   532.279 2368.109     test
50   96331.365 3860.628   889.910 2613.394     test
51  123798.621 3938.128   523.800 2221.460     test
52  157681.160 4468.267   701.588 3171.490     test
53  117281.768 2617.804   372.126 1947.747     test
54  119877.960 3622.936   689.156 2811.503     test
55  137222.381 4042.278   677.273 2260.035     test
56  134387.169 4986.101   417.990 2087.988     test
57   83356.588 6019.695   570.432 2537.676     test
58  115934.854 5059.858   653.492 2682.820     test
59  115303.708 4096.225   453.917 2299.879     test
60  118704.641 2937.360   531.971 2538.089     test
61   97507.367 4119.219   670.521 2832.585     test
62  129801.486 4243.791   628.920 2755.780     test
63  104971.223 3563.515   699.287 2791.011     test
64  109569.878 2268.947   346.463 2615.573     test
65  113732.668 3251.849   610.742 2366.822     test
66  152941.719 3209.693   414.224 2790.395     test
67  124669.003 1836.630   822.600 2286.715     test
68  120513.457 3409.268   604.923 2633.403     test
69  117989.246 3411.711   854.129 2260.631     test
70  158605.920 2736.410   748.497 2189.613     test
71  141367.848 3924.592   501.009 2786.146     test
72  122860.396 3652.208   357.234 2464.663     test
73  140219.552 5232.712   524.908 2778.842     test
74  137231.175 3991.677   311.630 2551.243     test
75   79234.912 6002.214   382.047 2277.864     test
76  130702.239 3626.320   449.825 2530.841     test
77  116481.873 4702.782   472.454 2597.918     test
78   79033.835 4495.428   425.359 2595.858     test
79  102257.454 4800.068   521.311 2967.518     test

### A/B Testinin Hipotezin Tanımlanması

In [67]:
## Hipotezi tanımlayalım;

#HO : MU1 = MU2
#H1 : MU1 != MU2

#HO : control ve test grupları arasında anlamlı bir farklılık yoktur.
#H1 : control ve test grupları arasında anlamlı bir farklılık vardır.


# Kontrol ve test grubu için purchase (kazanç) ortalamalarını analiz edelim;
df.groupby("Group").agg({"Purchase":"mean"})

         Purchase
Group
control   550.894
test      582.106

### Hipotez Testinin Gerçekleştirilmesi

In [75]:
## Varsayım kontrollerini yapalım;

# ilk olarak normal dağılım varsayımını yapalım; (shapiro)

#HO : dağılım normaldir.
#H1 : dağılım normal değildir.

# control sınıfının dağılımını incelemek için.
t_test,pvalue = shapiro(df.loc [df["Group"] == "control","Purchase"])
print("CONTROL SINIFI DAĞILIM VARSAYIMI ANALİZİ \n\nt_test: %.4f \np_value : %.4f\n-" % (t_test,pvalue))

# test sınıfının dağılımını incelemek için.
t_test,pvalue = shapiro(df.loc [df["Group"] == "test","Purchase"])
print("TEST SINIFI DAĞILIM VARSAYIMI ANALİZİ \n\nt_test: %.4f \np_value : %.4f" % (t_test,pvalue))

# P_value > 0.05 olduğu için HO hipotezini red edemiyoruz.
# Dağılım normaldir.

CONTROL SINIFI DAĞILIM VARSAYIMI ANALİZİ

t_test: 0.9773
p_value : 0.5891
-
TEST SINIFI DAĞILIM VARSAYIMI ANALİZİ

t_test: 0.9589
p_value : 0.1541

In [77]:
# 2. olarak varyans analizi kontrolü yapalım; (levene)

#HO : Varyans Homojendir.
#H1 : Varyans Homojen değildir.

t_test,pvalue = levene(df.loc [df["Group"] == "control","Purchase"],df.loc [df["Group"] == "test","Purchase"])
print("Varyans Analizi \n\nt_test: %.4f \np_value : %.4f\n-" % (t_test,pvalue))

# P_value > 0.05 olduğu için HO hipotezini red edemiyoruz.
# Varyans homojendir.

Varyans Analizi

t_test: 2.6393
p_value : 0.1083
-

In [78]:
# T örneklem testininin uygulamasını yapalım; 

#HO : control ve test grupları arasında anlamlı bir farklılık yoktur.
#H1 : control ve test grupları arasında anlamlı bir farklılık vardır.


# Normal dağılım sağlandığı için ttest_ind fonksiyonunu kullnacağız.
# Varyans homojenliği sağlandığı için =True olacak.


t_test,pvalue = ttest_ind(df.loc [df["Group"] == "control","Purchase"],df.loc [df["Group"] == "test","Purchase"],equal_var=True)
print("Varyans Analizi \n\nt_test: %.4f \np_value : %.4f\n-" % (t_test,pvalue))

# P value değeri < 0.05 sağlamadığı için HO red edilemez.
# Sonuç: control ve test grupları arasında anlamlı bir farklılık yoktur.

Varyans Analizi

t_test: -0.9416
p_value : 0.3493
-

## Sonuçların Analizi:

**Yöntem**:

*Hipotez sürecinde normallik varsayımı için shapiro, varyans homojenliği varsayımı için de levene testini uyguladım. İki varsayım da sağlandığı için parametrik test olarak Bağımsız T örneklem testini yani ttest_ind fonksiyonunu kullandım. Dağılım homojen olduğu için de equeal_var parametresini True olarak belirledim.*

**Tavsiye**:

*Bilimsel olarak kanıtlanıldığı gibi maximumbidding ve average biddng yöntemi arasında kayda değer bir farklılık bulunmamaktadır. İş tavsiyesi olarak kazanç sağlamayan yeni özelliğe daha fazla zaman ve sermaye yatırımı yapılmamalı proje iptal edilmelidir.*